[package]
name = "widerror"
version = "0.1.0"
edition = "2021"
description = "Error type with wide attributes, used for API unified error code."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
